---
AWSTemplateFormatVersion: '2010-09-09'
Description: cf notify stack
Parameters:
  HookUrl:
    Description: Slack webhook URL; see https://example.slack.com/apps/
    Type: String
    Default: https://hooks.slack.com/services/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
  Channel:
    Description: Channel name to post to (optional)
    Type: String
    Default: cf-notifications-poc

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda function to post CF updates to Slack
      Handler: sns_error.lambda_handler
      Policies: CloudWatchReadOnlyAccess 
      CodeUri: ./sns-error.zip
      Runtime: python2.7
      Timeout: 300
      AutoPublishAlias: "live"
      Environment:
        Variables:
          WEBHOOK: !Ref HookUrl
          CHANNEL: !Ref Channel
Outputs:
  CFNotifyEventSource:
    Description: ARN of CF SNS Topic
    Value:
      Ref: CFNotifyTopic
