#
# If you wish to deploy to multiple regions from a single git repo (verses the alternative of running a git repo per
# region with a GitFormation deployed for each of those repos, in their respective region) then you must deploy this
# stack in each region.
#
# This stack will setup the SNS topic for CloudFormation events in each region that the CF events in that region will
# pipe to. CloudFormation does not support cross-region SNS publishing. So this is a "shim" to assist with that process.
#


AWSTemplateFormatVersion: '2010-09-09'
Description: "GitFormation: Multi-Region Support Stack"
Parameters:
  GitFormationStackName:
    Description: "The name you gave the GitFormation stack"
    Type: String

  GitFormationPrimaryRegion:
    Description: "The region the GitFormation app is running in"
    Type: String

  AccountIds:
    Description: "The comma delimited list of account ID's that can this instance of GitFormation can automatically deploy to."
    Type: CommaDelimitedList

Resources:
  CloudFormationEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${GitFormationStackName}-CloudFormationEventsTopic"
      Subscription:
      - Endpoint: !Sub "arn:aws:lambda:${GitFormationPrimaryRegion}:${AWS::AccountId}:function:${GitFormationStackName}-CFEventsNotification"
        Protocol: lambda

  CloudFormationEventsSNSPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref CloudFormationEventsTopic
      PolicyDocument:
        Id: S3TopicPolicy
        Version: '2012-10-17'
        Statement:
          - Sid: "PublishEvents"
            Effect: Allow
            Principal:
              AWS: !Ref AccountIds
            Action: sns:Publish
            Resource: !Ref CloudFormationEventsTopic
