#
# Deployment Stack
# Typically used for as a Stack Set template - this creates the role that the CF Automation will use to launch the stacks in various accounts
#
---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  RoleName:
    Description: "The name of the IAM Role that will be created in each of the accounts. This name is provided to the deployer stack"
    Type: String
    Default: "CF-Automated-Deploy"

  ExecutionRoleManagedPolicies:
    Description: "List of IAM Policy ARNs that grant / restrict access to what kinds of stack resources can be created via the automation"
    Type: CommaDelimitedList
    Default: "arn:aws:iam::aws:policy/AdministratorAccess"

  DeployerAccountId:
    Description: "The Account ID that the automated deployer is running in"
    Type: Number

Resources:
  CFAutomationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${DeployerAccountId}:root"
            Action:
              - sts:AssumeRole
      Path: "/"
      RoleName: !Ref RoleName
      ManagedPolicyArns: !Ref ExecutionRoleManagedPolicies
